version: 2

updates:
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    assignees:
      - ericodx
    reviewers:
      - ericodx
    labels:
      - "dependencies"
      - "swift"
      - "spm"
      - "auto-update"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    assignees:
      - ericodx
    reviewers:
      - ericodx
    labels:
      - "dependencies"
      - "github-actions"
      - "auto-update"
